apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pv-claim
  namespace: n8n
spec:
  storageClassName: kube-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi