apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ${postgres_user_encoded}
  POSTGRES_PASSWORD: ${postgres_password_encoded}
  POSTGRES_DB: ${postgres_db_encoded}
  POSTGRES_NON_ROOT_USER: ${postgres_non_root_user_encoded}
  POSTGRES_NON_ROOT_PASSWORD: ${postgres_non_root_password_encoded}