deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1          
  server:
    http_listen_port: 3100
  analytics:
    reporting_enabled: false

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage_config:
    filesystem:
      directory: /var/loki           

  compactor:
    working_directory: /var/loki/compactor
    delete_request_cancel_period: 24h

  limits_config:
    retention_period: 672h           

persistence:
  enabled: true
  existingClaim: loki-pv-claim
