apiVersion: v1
kind: Secret
metadata:
  namespace: keycloak
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: ${keycloak_admin_encoded}
  KEYCLOAK_ADMIN_PASSWORD: ${keycloak_admin_password_encoded}
