apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: jenkins
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ${aws_access_key_id_encoded}
    AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key_encoded}
    AWS_DEFAULT_REGION: ${aws_default_region_encoded}
    AWS_ACCOUNT_ID: ${aws_account_id_encoded}
