apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-update-service-account
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-authorization-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-aws-authorization-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: aws-authorization-cluster-role
subjects:
- kind: ServiceAccount
  name: ecr-update-service-account
  namespace: infrastructure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-secret-update
  namespace: infrastructure
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: ecr-update-service-account
          restartPolicy: Never
          containers:
          - name: aws-ecr-secret-update
            image: localhost:32000/awsecr
            imagePullPolicy: Always
            env:
              - name: NAMESPACES
                value: ${namespaces}
            envFrom:
              - secretRef:
                  name: aws-credentials
