apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kube-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: ubuntu-slave1
  share: /srv/kube-lv
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.2