apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kube-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: ${nfs_server_ip}
  share: /srv/kube-lv
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - auto
  - nofail
  - nolock
  - intr
  - tcp
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: ${nfs_server_ip}
  share: /srv/nfs-lv
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - auto
  - nofail
  - nolock
  - intr
  - tcp
