apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-route53-update-service-account
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-certificates-cluster-role
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get","update","patch","list"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get","update","patch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-certificates-role-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: get-certificates-cluster-role
subjects:
- kind: ServiceAccount
  name: aws-route53-update-service-account
  namespace: infrastructure
---
apiVersion: v1
kind: Pod
metadata:
  name: "awsdns"
  namespace: infrastructure
  labels:
    app: "awsdns"
spec:
  serviceAccountName: aws-route53-update-service-account
  containers:
  - name: awsdns
    image: localhost:32000/awsdns
    imagePullPolicy: Always
    env:
      - name: RUN_INTERVAL
        value: "30"
      - name: KUBE_HOST_IP
        value: "${kube_host_ip}"
    envFrom:
      - secretRef:
          name: aws-credentials
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: local-registry
            operator: In
            values:
            - "yes"
