apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer-prod
  namespace: infrastructure
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: johnkoepp@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          hostedZoneID: ${aws_hosted_zone_id}
          region: ${aws_default_region}
          accessKeyID: ${aws_access_key_id}
          secretAccessKeySecretRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer-stage
  namespace: infrastructure
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: johnkoepp@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
      - dns01:
          route53:
            hostedZoneID: ${aws_hosted_zone_id}
            region: ${aws_default_region}
            accessKeyID: ${aws_access_key_id}
            secretAccessKeySecretRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
