apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-wired
  namespace: metallb-system
spec:
  ipAddressPools: ["default-addresspool"]
  nodeSelectors:
    - matchLabels:
        net: wired
  # optional: also pin specific NICs if names are consistent
  # interfaces:
  #   - eno1
  #   - enp3s0
