apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
        - name: PILOT_TRACE_SAMPLING
          value: "100"
        - name: PILOT_ENABLE_ALPHA_GATEWAY_API
          value: "true"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
