apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: box-quarantine-state
  namespace: box
spec:
  storageClassName: kube-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "${PVC_SIZE}"
