apiVersion: v1
kind: Secret
metadata:
  name: jenkins-aws-credentials
  namespace: ${JENKINS_NAMESPACE}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${jenkins_ecr_push_access_key_id_encoded}
  AWS_SECRET_ACCESS_KEY: ${jenkins_ecr_push_secret_access_key_encoded}
  AWS_DEFAULT_REGION: ${jenkins_ecr_push_default_region_encoded}
