apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: ${JENKINS_NAMESPACE}
type: Opaque
data:
  GITHUB_TOKEN: ${github_token_encoded}
  GITHUB_WEBHOOK_SECRET: ${github_webhook_secret_encoded}
