apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: ${JENKINS_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${JENKINS_STORAGE_CLASS}
  resources:
    requests:
      storage: ${JENKINS_STORAGE_SIZE}
